name: Download, Unzip and Replace Files

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Zip File
        run: |
          wget -O temp_file.zip "https://www.dropbox.com/scl/fi/wgez0ta6u2whq2lophhqy/MultiProfileWebView_NO_WORKFLOW.zip?rlkey=qld9ku6ds4trr1bisg8shc1so&st=0rfb63v4&dl=1"
      - name: Unzip File
        run: |
          mkdir temp
          unzip temp_file.zip -d temp/
      - name: Replace Files (Super Safe Method)
        run: |
          # Bash er advance feature on kora holo
          shopt -s extglob dotglob
          
          echo "Cleaning old repo files..."
          # Ekti command ei .git, .github, temp, ar temp_file.zip chara baki shob delete korbe (Kono error charai)
          rm -rf !(.git|.github|temp|temp_file.zip)
          
          echo "Copying new files from temp to root..."
          cp -r temp/* . || true
          
          echo "Cleaning up temp folder and zip..."
          rm -rf temp temp_file.zip
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git commit -m "Auto-update: Files extracted from zip" || echo "No changes to commit"
          git push
